project:
  type: website
  output-dir: docs

lang: ja

website:
  title: "CI4SS@Kandai"
  site-url: "https://www.jaysong.net/kandai-ci/"
  page-navigation: true
  favicon: figs/favicon.png
  page-footer: 
    right:
      - text: "© 2025 Jaehyun Song"
      - icon: house-fill
        href: https://www.jaysong.net
      - icon: github
        href: https://github.com/JaehyunSong
  navbar:
    logo: figs/logo.png
    search: true
    background: "#1955A6"
    pinned: true
    left:
      - text: "シラバス"
        href: syllabus.qmd
      - sidebar:intro
      - sidebar:material
      - text: "セッション情報"
        href: session.qmd
  sidebar:
    - id: intro
      title: "Rの使い方"
      style: "docked"
      contents:
        - intro/install.qmd
        - intro/rstudio.qmd
        - intro/filesystem.qmd
        - intro/project.qmd
        - intro/file.qmd
        - text: "パッケージ"
          href: intro/packages.qmd
    - id: material
      title: "講義資料"
      style: "docked"
      contents:
        - material/intro.qmd
        - material/foundation.qmd
        - material/rct.qmd
        - material/r.qmd
        - material/matching.qmd
        - material/did.qmd
        - material/rdd.qmd
        #- material/iv.qmd
  google-analytics: "G-9D5YDZ704S"

format:
  html:
    theme: 
      light: [a11y, styles.scss]
    css: styles.css

excute:
  freeze: true