---
title: "本講義について"
toc: true
toc-title: "目次"
---

```{r}
#| include: false
knitr::opts_chunk$set(fig.align = "center",
                      dev       = "ragg_png")
```

## 概要

* 科目名: 社会科学における因果推論
* 講師: 宋財泫 (ソン ジェヒョン)
* 所属: 関西大学総合情報学部
   * E-mail: song [*at*] kansai-u.ac.jp
   * Homepage: <https://www.jaysong.net>
* 時間: 月曜日2限
* 教室: ？？？

## 授業の内容

　本講義は、近年社会科学において関心が高まっている「因果推論」を行うための諸手段を理解・習得することを目的とする。最初に、最良の因果推論とも称される RCT(ランダム化比較試験)を説明し、RCTが不可能な際の手法としてマッチング、回帰不連続デザイン、差分の差分法、操作変数法などを紹介する。

## 評価

* 平常点: 70%
   * 授業への参加度、質問など
* 期末課題: 30%
   * 第16回の研究構想の発表

## 履修上の注意

　統計学に関する基礎知識が必要である。目安は母平均の差の検定、および線形回帰分析が理解でき、統計ソフトウェアで実行・解釈が可能なレベルである。

　本講義における共通言語はRである。Rの使い方に関しては既にインターネット上に膨大な情報がある。[宋](https://www.jaysong.net)と[矢内勇生](https://yukiyanai.github.io/)(高知工科大学)が執筆中の以下の資料(無料で閲覧可能)を参照することも1つの選択肢である。

* 宋財泫・矢内勇生. 『[私たちの R: ベストプラクティスの探究](https://www.jaysong.net/RBook/)』(web-book)
   * Rの導入方法は講義中、宋が解説する。

　統計学および定量的分析、Rの使い方については以下の書籍を講義開始日までに読んで
おくことを強く推奨する。

* 浅野正彦・矢内勇生. 2019『[Rによる計量政治学](https://www.amazon.co.jp/dp/4274223132)』オーム社.

　R スクリプト作成の際、{tidyverse} というパッケージ群を積極的に活用する。この パッケージには {dplyr}、{ggplot2} などのパッケージが含まれている。各パッケージの 使い方を習得するには以下の教材を推奨する。

* Wickham, Hadley and Grolemund, Garrett. 2017. [*R for Data Science: Import, Tidy, Transform, Visualize, and Model Data,*](https://www.amazon.co.jp/dp/1491910399/) O’Reilly. ([邦訳](www.amazon.co.jp/dp/487311814X/)あり/[原著](https://r4ds.had.co.nz)はインターネットから無料で閲覧可)
* 松村優哉・湯谷啓明・紀ノ定保礼・前田和寛 . 2021. 『[改訂2版 Rユーザのための RStudio[実践] 入門—tidyverseによるモダンな分析フローの世界—](https://www.amazon.co.jp/dp/4297121700/)』技術評論社.

## 教科書・参考書

以下は本書の内容を(一部)カバーする書籍の目録である。必ずしも購入する必要はないが、予習・復習において適宜参照することを推奨する。

* 因果推論の理論と実例
   * Angrist, Joahua D., and Jorn-steffen Pischke. 2008. [*Mostly Harmless Econometrics: An Empiricist’s Companion.*](http://amzn.asia/d/2TJ1HXE) Princeton University Press.
      * 『[「ほとんど無害」な計量経済学―応用経済学のための実証分析ガイド](http://amzn.asia/d/3JwCmNG)』 (翻訳はかなり有害)
   * Angrist, Joahua D., and Jorn-steffen Pischke. 2014. [*Mastering ’Metrics: The Path from Cause to Effect.*](http://amzn.asia/d/fIkurDl) Princeton University Press.
   * 森田果. 2014.『[実証分析入門—データから「因果関係」を読み解く作法](http://amzn.asia/d/g0ADpxT)』日本評論社.
   * 中室牧子・津川友介. 2017.『[「原因と結果」の経済学—データから真実を見抜く思考法](http://amzn.asia/d/gQN4bLu)』ダイヤモンド社.
   * 伊藤公一郎. 2017.『[データ分析の力—因果関係に迫る思考法](http://amzn.asia/d/avVVT5S)』光文社新書.
   * 松林哲也. 2021.『[政治学と因果推論](https://www.amazon.co.jp/dp/4000269992/)』岩波書店.
* 理論+R
   * 星野匡郎・田中久稔. 2016.『[Rによる実証分析—回帰分析から因果分析へ—](http://amzn.asia/d/0LFlZqm)』オーム社.
   * 安井翔太. 2020. 『[効果検証入門—正しい比較のための因果推論/計量経済学の基礎](https://www.amazon.co.jp/dp/4297111179)』技術評論社.
   * Cunningham, Scott. 2021. [*Causal Inference: The Mixtape.*](https://mixtape.scunning.com/) Yale University Press.
   * 高橋将宜. 2022. 『[統計的因果推論の理論と実装](https://www.amazon.co.jp/dp/4320112458/)』共立出版.

## 講義内容

以下の内容は履修者の理解度や進捗状況に応じて変更される可能性がある。

1. ガイダンス
2. 因果推論の考え方
3. ランダム化比較試験
4. 分析ツールの使い方
5. 分析ツールの使い方（続き）
6. 回帰分析と因果推論
7. マッチング（理論）
8. マッチング（実習）
9. 差分の差分法（理論）
10. 差分の差分法（実習）
11. 回帰不連続デザイン（理論）
12. 回帰不連続デザイン（実習）
13. 操作変数法（理論）
14. 操作変数法（実習）
15. 研究構想の発表